module.exports.config = {
  name: "yaytext",
  version: "1.0.0",
  hasPermssion: 0,
  credits: "𝑪𝒐̂𝒏𝒈 𝑻𝒉𝒂̀𝒏𝒉",
  description: "𝑐ℎ𝑢𝑦𝑒̂̉𝑛 𝑓𝑜𝑛𝑡 𝑐ℎ𝑢̛̃ ( 𝑐𝑜́ 𝑑𝑎̂́𝑢 )",
  commandCategory: "game",
  usages: "yaytext <nội dung>",
  cooldowns: 5
};

module.exports.run = async ({ event, api, args }) => {
 var text = args.join("");
     text = text;
       text = text.replace(/ /g, ` `)
.replace(/a/g, `𝑎`)
.replace(/á/g, `𝑎́`)
.replace(/à/g, `𝑎̀`)
.replace(/ã/g, `𝑎̃`)
.replace(/ạ/g, `𝑎̣`)
.replace(/ả/g, `𝑎̉`)
.replace(/ă/g, `𝑎̆`)
.replace(/ắ/g, `𝑎̆́`)
.replace(/ằ/g, `𝑎̆̀`)
.replace(/ẵ/g, `𝑎̆̃`)
.replace(/ặ/g, `𝑎̣̆`)
.replace(/ẳ/g, `𝑎̆̉`)
.replace(/â/g, `𝑎̂`)
.replace(/ấ/g, `𝑎̂́`)
.replace(/ầ/g, `𝑎̂̀`)
.replace(/ẫ/g, `𝑎̂̃`)
.replace(/ậ/g, `𝑎̣̂`)
.replace(/ấ/g, `𝑎̂̉`)
.replace(/b/g, `𝑏`)
.replace(/c/g, `𝑐`)
.replace(/d/g, `𝑑`)
.replace(/d/g, `đ`)
.replace(/e/g, `𝑒`)
.replace(/é/g, `𝑒́`)
.replace(/è/g, `𝑒̀`)
.replace(/ẽ/g, `𝑒̃`)
.replace(/ẹ/g, `𝑒̣`)
.replace(/ẻ/g, `𝑒̉`)
.replace(/ê/g, `𝑒̂`)
.replace(/ế/g, `𝑒̂́`)
.replace(/ề/g, `𝑒̂̀`)
.replace(/ễ/g, `𝑒̂̃`)
.replace(/ệ/g, `𝑒̣̂`)
.replace(/ể/g, `𝑒̂̉`)
.replace(/f/g, `𝑓`)
.replace(/g/g, `𝑔`)
.replace(/h/g, `ℎ`)
.replace(/i/g, `𝑖`)
.replace(/í/g, `𝑖́`)
.replace(/ì/g, `𝑖̀`)
.replace(/ĩ/g, `𝑖̃`)
.replace(/ỉ/g, `𝑖̉`)
.replace(/ị/g, `𝑖̣`)
.replace(/j/g, `𝑗`)
.replace(/k/g, `𝑘`)
.replace(/l/g, `𝑙`)
.replace(/m/g, `𝑚`)
.replace(/n/g, `𝑛`)
.replace(/o/g, `𝑜`)
.replace(/ó/g, `𝑜́`)
.replace(/ò/g, `𝑜̀`)
.replace(/õ/g, `𝑜̃`)
.replace(/ọ/g, `𝑜̣`)
.replace(/ỏ/g, `𝑜̉`)
.replace(/ô/g, `𝑜̂`)
.replace(/ố/g, `𝑜̂́`)
.replace(/ồ/g, `𝑜̂̀`)
.replace(/ỗ/g, `𝑜̂̃`)
.replace(/ộ/g, `𝑜̣̂`)
.replace(/ổ/g, `𝑜̂̉`)
.replace(/ơ/g, `𝑜̛`)
.replace(/ớ/g, `𝑜̛́`)
.replace(/ờ/g, `𝑜̛̀`)
.replace(/ỡ/g, `𝑜̛̃`)
.replace(/ợ/g, `𝑜̛̣`)
.replace(/ở/g, `𝑜̛̉`)
.replace(/p/g, `𝑝`)
.replace(/q/g, `𝑞`)
.replace(/r/g, `𝑟`)
.replace(/s/g, `𝑠`)
.replace(/t/g, `𝑡`)
.replace(/u/g, `𝑢`)
.replace(/ú/g, `𝑢́`)
.replace(/ù/g, `𝑢̀`)
.replace(/ũ/g, `𝑢̃`)
.replace(/ụ/g, `𝑢̣`)
.replace(/ủ/g, `𝑢̉`)
.replace(/ư/g, `𝑢̛`)
.replace(/ứ/g, `𝑢̛́`)
.replace(/ừ/g, `𝑢̛̀`)
.replace(/ữ/g, `𝑢̛̃`)
.replace(/ự/g, `𝑢̛̣`)
.replace(/ử/g, `𝑢̛̉`)
.replace(/v/g, `𝑣`)
.replace(/x/g, `𝑥`)
.replace(/y/g, `𝑦`)
.replace(/ý/g, `𝑦́`)
.replace(/ỳ/g, `𝑦̀`)
.replace(/ỹ/g, `𝑦̃`)
.replace(/ỵ/g, `𝑦̣`)
.replace(/ỷ/g, `𝑦̉`)
.replace(/w/g, `𝑤`)
.replace(/z/g, `𝑧`)
.replace(/Q/g, `𝑄`)
.replace(/W/g, `𝑊`)
.replace(/E/g, `𝐸`)
.replace(/R/g, `𝑅`)
.replace(/T/g, `𝑇`)
.replace(/Y/g, `𝑌`)
.replace(/U/g, `𝑈`)
.replace(/I/g, `𝐼`)
.replace(/O/g, `𝑂`)
.replace(/P/g, `𝑃`)
.replace(/A/g, `𝐴`)
.replace(/S/g, `𝑆`)
.replace(/D/g, `𝐷`)
.replace(/F/g, `𝐹`)
.replace(/G/g, `𝐺`)
.replace(/H/g, `𝐻`)
.replace(/J/g, `𝐽`)
.replace(/K/g, `𝐾`)
.replace(/L/g, `𝐿`)
.replace(/Z/g, `𝑍`)
.replace(/X/g, `𝑋`)
.replace(/C/g, `𝐶`)
.replace(/V/g, `𝑉`)
.replace(/B/g, `𝐵`)
.replace(/N/g, `𝑁`)
.replace(/M/g, `𝑀`)
.replace(/Ú/g, `𝑈́`)
.replace(/Ù/g, `𝑈̀`)
.replace(/Ủ/g, `𝑈̉`)
.replace(/Ũ/g, `𝑈̃`)
.replace(/Ụ/g, `𝑈̣`)
.replace(/Ứ/g, `𝑈̛́`)
.replace(/Ừ/g, `𝑈̛̀`)
.replace(/Ử/g, `𝑈̛̉`)
.replace(/Ữ/g, `𝑈̛̃`)
.replace(/Ự/g, `𝑈̛̣`)
.replace(/Ế/g, `𝐸̂́`)
.replace(/Ề/g, `𝐸̂̀`)
.replace(/Ể/g, `𝐸̂̉`)
.replace(/Ễ/g, `𝐸̂̃`)
.replace(/Ệ/g, `𝐸̣̂`)
.replace(/É/g, `𝐸́`)
.replace(/È/g, `𝐸̀`)
.replace(/Ẻ/g, `𝐸̉`)
.replace(/Ẽ/g, `𝐸̃`)
.replace(/Ẹ/g, `𝐸̣`)
.replace(/Ó/g, `𝑂́`)
.replace(/Ò/g, `𝑂̀`)
.replace(/Ỏ/g, `𝑂̉`)
.replace(/Õ/g, `𝑂̃`)
.replace(/Ọ/g, `𝑂̣`)
.replace(/Á/g, `𝐴́`)
.replace(/À/g, `𝐴̀`)
.replace(/Ả/g, `𝐴̉`)
.replace(/Ã/g, `𝐴̃`)
.replace(/Ạ/g, `𝐴̣`)
.replace(/Ắ/g, `𝐴̆́`)
.replace(/Ằ/g, `𝐴̆̀`)
.replace(/Ẳ/g, `𝐴̆̉`)
.replace(/Ẵ/g, `𝐴̆̃`)
.replace(/Ặ/g, `𝐴̣̆`)
.replace(/Ấ/g, `𝐴̂́`)
.replace(/Ầ/g, `𝐴̂̀`)
.replace(/Ẩ/g, `𝐴̂̉`)
.replace(/Ẫ/g, `𝐴̂̃`)
.replace(/Ậ/g, `𝐴̣̂`)
.replace(/Đ/g, `Đ`)
.replace(/Ý/g, `𝑌́`)
.replace(/Ỳ/g, `𝑌̀`)
.replace(/Ỷ/g, `𝑌̃`)
.replace(/Ỹ/g, `𝑌̉`)
.replace(/Ỵ/g, `𝑌̣`)
.replace(/Í/g, `𝐼́`)
.replace(/Ì/g, `𝐼̀`)
.replace(/Ỉ/g, `𝐼̉`)
.replace(/Ĩ/g, `𝐼̃`)
.replace(/Ị/g, `𝐼̣`)
.replace(/Ố/g, `𝑂̂́`)
.replace(/Ồ/g, `𝑂̂̀`)
.replace(/Ổ/g, `𝑂̂̉`)
.replace(/Ỗ/g, `𝑂̂̃`)
.replace(/Ộ/g, `𝑂̣̂`)
.replace(/ /g, " ");
var arr = text.replace("\n", "").split("\n").filter(item => item.length != 0);
var num = (arr.length/6)-1;
var main = arr.slice(0,6);
var extra = arr.splice(6);
var msg = "";
var mainlength = main.length;
for(let i = 0; i < mainlength; i++) {
  var txt = main[i];
  for(let o = 0; o < num; o++) {
    txt += extra[i+(o*6)];
  }
  msg += txt+"\n";
}
return api.sendMessage(msg+""+"🦄💜 𝑪𝒐̂𝒏𝒈 𝑻𝒉𝒂̀𝒏𝒉 💜🦄", event.threadID, event.messageID);
}